version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    dependencies:
      pre:
        - sudo apt-get update; sudo apt-get install libboost-program-options-dev
     
    steps:
      - checkout
      - run:
          name: Compile the software
          command: make
      - run:
          name: print the date
          command: date

