version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Compile the software
          command: chmod +x ./build_debian.sh; ./build_debian.sh
      - run:
          name: print the date
          command: date

