version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
      
     
    steps:
      - checkout
      - run:
          name: Compile the software
          command: make
      - run:
          name: print the date
          command: date

